### ISSUE TITLE
detailed reference

### ISSUE THREAD

**Issue by daiwei9501** [GH920/Improve-Medical-Image-Classification-with-GAN#2]
I want to cite your article, May I ask what is the detailed reference?

**Comment by GH920** [comment]
Thanks for your interest. Our paper is still under review and you may first cite it as

> G. Huang, A. Jafari. "Improved balancing gan: Minority-class image generation." Accessed Oct 5, 2020. https://github.com/GH920/improved-bagan-gp/blob/master/article.pdf

If we have any updates, I will reply here for your information.

**Comment by daiwei9501** [comment]
Thank you for your kindness！

**Comment by GH920** [comment]
Hi @daiwei9501 , here is our first arxiv version of the paper. Please view the link https://arxiv.org/abs/2011.00189. 

For the updated reference,
> G. Huang, A. Jafari. "Improved balancing gan: Minority-class image generation." [Online]. Available: arXiv:2011.00189

**Comment by daiwei9501** [comment]
OK ！ Thank you again for your kindness！

**Comment by GH920** [comment]
Sure, with pleasure!

**Comment by GH920** [comment]
Hi, this is the published reference. I'll close this issue. Feel free to reopen it if you have any questions.
> Huang, G., Jafari, A.H. Enhanced balancing GAN: minority-class image generation. Neural Comput & Applic (2021). https://doi.org/10.1007/s00521-021-06163-8
