### ISSUE TITLE
https://storage.googleapis.com/exam-deep-learning/train.zip not available

### ISSUE THREAD

**Issue by xavier-lessage** [GH920/Improve-Medical-Image-Classification-with-GAN#4]
Hello,

I would like download this training set but the link sounds like not available.
It's possible to have this train.zip file with another link?

Thank you very much.

Kr,
Xavier

**Comment by GH920** [comment]
Sorry, that's the data given by another author (Amir Jafari). I don't have a backup of this dataset.
