### ISSUE TITLE
training loop question...epochs =2? 

### ISSUE THREAD

**Issue by hangar11** [GH920/Improve-Medical-Image-Classification-with-GAN#5]
Hello, 

I have a question regarding the training loop used (improved_bagan_gp.py, line 532). 
I understand why a training loop would be used with train_on_batch to loop over the training steps and epochs, in some cases it is also used with model.fit. However I'm struggling to understand...why use a training for loop over model.fit with epochs=2 instead of epochs =1? 

Thanks in advance

**Comment by GH920** [comment]
Sorry for the confusion. The reason I looped over the model.fit() is for visualization of training results. epoch=2 means the model will be trained 2 epochs per visualization. Actually, you could use a custom [Keras callback](https://www.tensorflow.org/api_docs/python/tf/keras/callbacks/Callback) at on_epoch_end to plot the generated images vs real images. 
https://github.com/GH920/improved-bagan-gp/blob/74659397e84d5d531e2fbed1eb5bf7d6cfc66bbe/codes/improved_bagan_gp.py#L531-L539
