### ISSUE TITLE
model save problem

### ISSUE THREAD

**Issue by bbchond** [GH920/Improve-Medical-Image-Classification-with-GAN#6]
Hi, dear authors.
After training the improved bagan, I tried to save the generator and discriminator models with codes below:

from tensorflow.keras.models import load_model
bagan_gp.generator.save('bagan_generator.h5')
bagan_gp.discriminator.save('bagan_discriminator.h5')

However, I got the warning as below:
WARNING:tensorflow:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

I wonder how to correctly save the generator and discriminator models of the improved balance adversarial network.
Thank you in advance.

**Comment by GH920** [comment]
Hi @bbchond , it's not an error and will not hurt the saved model. That's the warning in tensorflow>2.3 (I tried 2.6, not sure on other versions like 2.4, 2.5, 2.7) when you use model.save() with your customized model.

**Comment by bbchond** [comment]
Hi, @GH920. After receiving your reply, I employed the saved model to verify and successfully completed the experiment. Thank you very much for your work.
