### ISSUE TITLE
细胞数据集

### ISSUE THREAD

**Issue by 1183371714** [GH920/Improve-Medical-Image-Classification-with-GAN#9]
您好，能提供一下细胞数据集吗？我着急使用，但是无法联系上另外一个作者。 哭~~~

**Comment by GH920** [comment]
不好意思，这个数据集是另一位作者的，他以前公开在googleAPIs里。我没有公开这个数据的权限。

Sorry, I have no right to publish this dataset (cell) as it was created by another author Dr. Jafari. FYI, the dataset was public two years ago.
